---
title: "CrossTalk Archaeology Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(shiny)
library(leaflet)
library(crosstalk)
library(d3scatter)
library(DT)
library(readr)
library(flexdashboard)
library(tidyverse)

sitecoor2 <- read_csv("sitecoor2.csv")
s<-sitecoor2 %>% mutate(perc=round((Slag/sum(Slag))*100,2))
sd <- SharedData$new(s)
```

Linked GIS/Tables/Plots
=======================================================================

Column {data-width=600}
-------------------------------------
    
### Geographic Distribution of Sites
    
```{r}
renderLeaflet({
    leaflet(sd) %>%
      addProviderTiles(
        providers$Esri.WorldImagery, group = "World Imagery") %>%
      addCircleMarkers(weight=2,
                       stroke=TRUE,
                       color="black",
                       opacity = 1,
                       fill=TRUE,
                       fillColor = "white",
                       fillOpacity = 1)
  })
```
   
Column {data-width=400}
-------------------------------------
   
### Tabular Data  

```{r table}
table<-DT::renderDataTable({
    datatable(sd, 
              extensions="Scroller",
              style="bootstrap",
              class="compact",
              width="100%",
              options=list(
                deferRender=TRUE,
                scrollX = TRUE,
                scrollY=300,
                scroller=TRUE
                ), rownames= FALSE)
  }, server = FALSE)
table
```   
 
### Scatter Distribution of Data Points 
    
```{r}
renderD3scatter({
    d3scatter(sd, ~FeO, ~SiO2, width = "100%", height = 300, color = ~Country)
})
```

Column {data-width=100}
<!-- ------------------------------------- -->

<!-- ### Cumulative % of Iron -->

<!-- ```{r} -->
<!-- library(shiny) -->
<!-- library(tidyverse) -->
<!-- library(DT) -->
<!-- library(flexdashboard) -->
<!-- library(summarywidget) -->

<!-- selectedRow <- eventReactive(input$table_rows_current,{ -->
<!--       selrow<-sum(s$perc[c(input$table_rows_current)]) -->
<!--     }) -->

<!-- # observe({summarywidget(sd, 'sum','perc')}) -->

<!-- num<-summarywidget(sd, 'sum','perc') -->

<!-- # renderPrint({num()}) -->
<!-- # renderGauge({ -->
<!-- #   gauge( -->
<!-- #     num, min = 0, max = 100, symbol = '%', gaugeSectors(success = c(80, 100), warning = c(40, 79), danger = c(0, 39)) -->
<!-- #     ) -->
<!-- # }) -->
<!-- ``` -->

<!-- ### Cumulative % of Silica -->

<!-- ```{r} -->
<!-- rate <- 13 -->
<!-- gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors( -->
<!--   success = c(80, 100), warning = c(40, 79), danger = c(0, 39) -->
<!-- )) -->
<!-- ``` -->

<!-- ### Cumulative %  -->

<!-- ```{r} -->
<!-- rate <- 44 -->
<!-- gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors( -->
<!--   success = c(80, 100), warning = c(40, 79), danger = c(0, 39) -->
<!-- )) -->
<!-- ``` -->

<!-- ### Next -->

<!-- ```{r} -->
<!-- comp <- reactive({ -->
<!--   paste0(input$tableId_row_index) -->
<!--   }) -->

<!-- renderValueBox({ -->
<!--   test<-comp() -->
<!--   valueBox( -->
<!--     value = test, -->
<!--     icon = "fa-area-chart" -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### Thing -->

<!-- ```{r} -->
<!-- valueBox(34,  -->
<!--          icon = "fa-trash", -->
<!--          color = "warning") -->
<!-- ``` -->